name: Cleanup caches for closed branches

on:
  pull_request:
    types: [closed]
  workflow_dispatch: ~

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cleanup PR Actions Caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache || true

          REPO=${{ github.repository }}
          BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"

          echo "Fetching list of cache keys for branch $BRANCH..."
          cacheKeysForPR=$(gh actions-cache list -R "$REPO" -B "$BRANCH" | cut -f 1 || true)

          set +e
          for cacheKey in $cacheKeysForPR
          do
            if [ -n "$cacheKey" ]; then
              echo "Deleting cache key: $cacheKey"
              gh actions-cache delete "$cacheKey" -R "$REPO" -B "$BRANCH" --confirm || true
            fi
          done
          echo "Cache cleanup finished."
